### ISSUE TITLE
Dependency resolves to an apk which is not supported as a compliation dependency

### ISSUE THREAD

**Issue by arminghm** [melvinjlobo/MetaballMenu#2]
Hi.
First, thanks for the library.

I think you use "**com.android.application**" plugin instead "**com.android.library**" in your **build.gradle** file, then we can not compile it using gradle.
Could you please fix that. tanx :+1: 

I use this to add the dependency to my project :
`compile 'com.github.melvinjlobo:MetaballMenu:d0c3ff22fe'`

**Comment by mohammadrafigh** [comment]
+1

**Comment by melvinjlobo** [comment]
Hi, I did not intend the project to be used as a library since it's just a couple of files and can be simply included without other dependancies. I will make a note of it for the future. Thanks!
